/**
 * Harness-neutral agent base prompt convention.
 *
 * The global file is a regenerated template. Agent-scoped files are user-owned
 * complete stable base prefixes; runtime appends dynamic/context sections.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { resolveStateDir } from "../config/paths.js";
import type { OpenClawConfig } from "../config/types.openclaw.js";
import {
  AGENT_BASE_PROMPT_FILENAME,
  readAgentBasePrompt,
  resolveAgentBasePromptPath,
  sha256Text,
  type AgentBasePrompt,
} from "./agent-base-prompt-file.js";
import { resolveGpt5SystemPromptContribution } from "./gpt5-prompt-overlay.js";
import { buildConfiguredAgentSystemPrompt } from "./system-prompt-config.js";

const AGENT_BASE_TEMPLATE_HEADER = `<!--
Generated by OpenClaw. Do not edit this file in place.

Copy this template to an agent directory as agent-base.md to make it the
stable base prompt prefix for that agent. Agent-scoped copies are user-owned
and are never regenerated or overwritten by gateway startup.
-->`;

export type AgentBasePromptTemplate = {
  source: "generated-template";
  path: string;
  text: string;
  fingerprint: string;
};

export {
  AGENT_BASE_PROMPT_FILENAME,
  readAgentBasePrompt,
  resolveAgentBasePromptPath,
  type AgentBasePrompt,
};

export function resolveAgentBasePromptTemplatePath(params?: {
  stateDir?: string;
  env?: NodeJS.ProcessEnv;
}): string {
  return path.join(params?.stateDir ?? resolveStateDir(params?.env), AGENT_BASE_PROMPT_FILENAME);
}

export function buildAgentBasePromptTemplate(params?: {
  config?: OpenClawConfig;
  workspaceDir?: string;
  userTimezone?: string;
  agentId?: string;
}): string {
  const promptContribution = resolveGpt5SystemPromptContribution({
    config: params?.config,
    providerId: "codex",
    modelId: "gpt-5",
  });
  const body = buildConfiguredAgentSystemPrompt({
    config: params?.config,
    agentId: params?.agentId,
    workspaceDir: params?.workspaceDir ?? "<workspace>",
    userTimezone: params?.userTimezone,
    promptSurface: "openclaw_main",
    toolNames: [],
    includeMemorySection: false,
    internalRenderMode: "agent_base_static_template",
    promptContribution,
  });
  return `${AGENT_BASE_TEMPLATE_HEADER}\n\n${body.trim()}\n`;
}

export async function ensureAgentBasePromptTemplate(params?: {
  stateDir?: string;
  env?: NodeJS.ProcessEnv;
  config?: OpenClawConfig;
  workspaceDir?: string;
  userTimezone?: string;
  agentId?: string;
}): Promise<AgentBasePromptTemplate> {
  const templatePath = resolveAgentBasePromptTemplatePath(params);
  const text = buildAgentBasePromptTemplate(params);
  await fs.mkdir(path.dirname(templatePath), { recursive: true });
  await fs.writeFile(templatePath, text, "utf8");
  return {
    source: "generated-template",
    path: templatePath,
    text,
    fingerprint: sha256Text(text),
  };
}
