/**
 * Codex app-server base prompt convention.
 *
 * The legacy global file is a regenerated template alias. Agent-scoped
 * app-server-base.md files remain supported for Codex compatibility, but the
 * canonical agent-owned base prompt file is agent-base.md.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { resolveStateDir } from "../config/paths.js";
import type { OpenClawConfig } from "../config/types.openclaw.js";
import { AGENT_BASE_PROMPT_FILENAME, sha256Text } from "./agent-base-prompt-file.js";
import {
  buildAgentBasePromptTemplate,
  ensureAgentBasePromptTemplate,
  resolveAgentBasePromptTemplatePath,
  type AgentBasePromptTemplate,
} from "./agent-base-prompt.js";
import { CODEX_APP_SERVER_BASE_PROMPT_FILENAME } from "./codex-app-server-base-prompt-file.js";
export {
  readCodexAppServerAgentBasePrompt,
  resolveCodexAppServerCanonicalAgentBasePromptPath,
  resolveCodexAppServerAgentBasePromptPath,
  type CodexAppServerAgentBasePrompt,
} from "./codex-app-server-base-prompt-file.js";

const TEMPLATE_HEADER = `<!--
Generated by OpenClaw. Do not edit this file in place.

This is a legacy Codex app-server template alias. Prefer copying
${AGENT_BASE_PROMPT_FILENAME} to an agent directory as ${AGENT_BASE_PROMPT_FILENAME}.
Agent-scoped copies are user-owned and are never regenerated or overwritten by
gateway startup. Codex still accepts app-server-base.md as a fallback when
agent-base.md is absent.
-->`;

export type CodexAppServerBasePromptTemplate = {
  source: "generated-template";
  path: string;
  text: string;
  fingerprint: string;
};

export function resolveCodexAppServerBasePromptTemplatePath(params?: {
  stateDir?: string;
  env?: NodeJS.ProcessEnv;
}): string {
  return path.join(
    params?.stateDir ?? resolveStateDir(params?.env),
    CODEX_APP_SERVER_BASE_PROMPT_FILENAME,
  );
}

export function buildCodexAppServerBasePromptTemplate(params?: {
  config?: OpenClawConfig;
  workspaceDir?: string;
  userTimezone?: string;
  agentId?: string;
}): string {
  const agentTemplate = buildAgentBasePromptTemplate(params);
  const body = agentTemplate.replace(/^<!--[\s\S]*?-->\n\n/, "");
  return `${TEMPLATE_HEADER}\n\n${body.trim()}\n`;
}

export async function ensureCodexAppServerBasePromptTemplate(params?: {
  stateDir?: string;
  env?: NodeJS.ProcessEnv;
  config?: OpenClawConfig;
  workspaceDir?: string;
  userTimezone?: string;
  agentId?: string;
}): Promise<CodexAppServerBasePromptTemplate> {
  const templatePath = resolveCodexAppServerBasePromptTemplatePath(params);
  const text = buildCodexAppServerBasePromptTemplate(params);
  await fs.mkdir(path.dirname(templatePath), { recursive: true });
  await fs.writeFile(templatePath, text, "utf8");
  return {
    source: "generated-template",
    path: templatePath,
    text,
    fingerprint: sha256Text(text),
  };
}

export async function ensureAgentAndCodexAppServerBasePromptTemplates(params?: {
  stateDir?: string;
  env?: NodeJS.ProcessEnv;
  config?: OpenClawConfig;
  workspaceDir?: string;
  userTimezone?: string;
  agentId?: string;
}): Promise<{
  agentBase: AgentBasePromptTemplate;
  codexAppServerBase: CodexAppServerBasePromptTemplate;
}> {
  const agentBase = await ensureAgentBasePromptTemplate(params);
  const codexAppServerBase = await ensureCodexAppServerBasePromptTemplate(params);
  return { agentBase, codexAppServerBase };
}

export { resolveAgentBasePromptTemplatePath };
