import { createHash } from "node:crypto";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import {
  buildAgentBasePromptTemplate,
  ensureAgentBasePromptTemplate,
  readAgentBasePrompt,
  resolveAgentBasePromptPath,
} from "./agent-base-prompt.js";
import {
  ensureAgentAndCodexAppServerBasePromptTemplates,
  ensureCodexAppServerBasePromptTemplate,
  readCodexAppServerAgentBasePrompt,
  resolveCodexAppServerAgentBasePromptPath,
} from "./codex-app-server-base-prompt.js";

let tempDir: string;

function sha256Text(text: string): string {
  return `sha256:${createHash("sha256").update(text, "utf8").digest("hex")}`;
}

describe("Codex app-server base prompt convention", () => {
  beforeEach(async () => {
    tempDir = await fs.mkdtemp(path.join(os.tmpdir(), "openclaw-codex-base-prompt-"));
  });

  afterEach(async () => {
    await fs.rm(tempDir, { recursive: true, force: true });
  });

  it("renders the generated canonical template with OpenClaw identity and GPT-5 behavior overlay", () => {
    const prompt = buildAgentBasePromptTemplate();

    expect(prompt).toContain("Generated by OpenClaw. Do not edit this file in place.");
    expect(prompt).toContain("agent-base.md");
    expect(prompt).toContain("You are a personal assistant running inside OpenClaw.");
    expect(prompt).toContain("<persona_latch>");
    expect(prompt).toContain("Be warm, collaborative, and quietly supportive");
    expect(prompt).toContain("Use only tools exposed directly by the active runtime.");
    expect(prompt).not.toContain("No OpenClaw tool list is injected");
    expect(prompt).not.toContain("OpenClaw lists the standard tools above");
  });

  it("excludes workspace context files, memory, skills, heartbeat, and TOOLS.md guidance", () => {
    const prompt = buildAgentBasePromptTemplate();

    expect(prompt).not.toContain("## Workspace");
    expect(prompt).not.toContain("Your working directory is:");
    expect(prompt).not.toContain("Treat this directory as the single global workspace");
    expect(prompt).not.toContain("OPENCLAW_CACHE_BOUNDARY");
    expect(prompt).not.toContain("<!-- OPENCLAW_CACHE_BOUNDARY -->");
    expect(prompt).not.toContain("## Messaging");
    expect(prompt).not.toContain("Runtime-generated completion events may ask for a user update.");
    expect(prompt).not.toContain("## Assistant Output Directives");
    expect(prompt).not.toContain("## Silent Replies");
    expect(prompt).not.toContain("## Current Date & Time");
    expect(prompt).not.toContain("session_status");
    expect(prompt).not.toContain("## Workspace Files (injected)");
    expect(prompt).not.toContain("# Project Context");
    expect(prompt).not.toContain("TOOLS.md is usage guidance");
    expect(prompt).not.toContain("AGENTS.md");
    expect(prompt).not.toContain("SOUL.md");
    expect(prompt).not.toContain("IDENTITY.md");
    expect(prompt).not.toContain("USER.md");
    expect(prompt).not.toContain("MEMORY.md");
    expect(prompt).not.toContain("HEARTBEAT.md");
    expect(prompt).not.toContain("## Skills");
    expect(prompt).not.toContain("## Voice (TTS)");
    expect(prompt).not.toContain("## Runtime");
    expect(prompt).not.toContain("Current model identity:");
    expect(prompt).not.toContain("Reasoning:");
    expect(prompt).not.toContain("<oai-mem-citation>");
  });

  it("honors GPT-5 overlay opt-out config while keeping the base behavior contract", () => {
    const prompt = buildAgentBasePromptTemplate({
      config: {
        agents: {
          defaults: {
            promptOverlays: {
              gpt5: { personality: "off" },
            },
          },
        },
      },
    });

    expect(prompt).toContain("<persona_latch>");
    expect(prompt).not.toContain("Be warm, collaborative, and quietly supportive");
  });

  it("reads a canonical agent override and fingerprints exact contents", async () => {
    const agentDir = path.join(tempDir, "agents", "sky", "agent");
    await fs.mkdir(agentDir, { recursive: true });
    const promptPath = resolveAgentBasePromptPath(agentDir);
    const text = "Sky base prompt\n\nwith exact trailing newline\n";
    await fs.writeFile(promptPath, text, "utf8");

    const result = await readAgentBasePrompt({ agentDir });

    expect(result).toEqual({
      source: "agent-file",
      path: promptPath,
      text,
      fingerprint: sha256Text(text),
    });
  });

  it("leaves runtime on the default path when the agent override is missing", async () => {
    await expect(readAgentBasePrompt({ agentDir: tempDir })).resolves.toEqual({
      source: "none",
    });
  });

  it("prefers agent-base.md over the Codex app-server compatibility fallback", async () => {
    const agentDir = path.join(tempDir, "agents", "sky", "agent");
    await fs.mkdir(agentDir, { recursive: true });
    const canonicalPath = resolveAgentBasePromptPath(agentDir);
    const legacyPath = resolveCodexAppServerAgentBasePromptPath(agentDir);
    await fs.writeFile(canonicalPath, "canonical base\n", "utf8");
    await fs.writeFile(legacyPath, "legacy base\n", "utf8");

    const result = await readCodexAppServerAgentBasePrompt({ agentDir });

    expect(result).toEqual({
      source: "agent-file",
      path: canonicalPath,
      text: "canonical base\n",
      fingerprint: sha256Text("canonical base\n"),
    });
  });

  it("falls back to app-server-base.md for Codex compatibility", async () => {
    const agentDir = path.join(tempDir, "agents", "sky", "agent");
    await fs.mkdir(agentDir, { recursive: true });
    const legacyPath = resolveCodexAppServerAgentBasePromptPath(agentDir);
    await fs.writeFile(legacyPath, "legacy base\n", "utf8");

    const result = await readCodexAppServerAgentBasePrompt({ agentDir });

    expect(result).toEqual({
      source: "agent-file",
      path: legacyPath,
      text: "legacy base\n",
      fingerprint: sha256Text("legacy base\n"),
    });
  });

  it("writes the global templates without touching agent-scoped prompt files", async () => {
    const agentDir = path.join(tempDir, "agents", "sky", "agent");
    const agentPromptPath = resolveAgentBasePromptPath(agentDir);
    const agentPrompt = "custom agent base\n";
    await fs.mkdir(agentDir, { recursive: true });
    await fs.writeFile(agentPromptPath, agentPrompt, "utf8");

    const result = await ensureAgentAndCodexAppServerBasePromptTemplates({ stateDir: tempDir });

    await expect(fs.readFile(result.agentBase.path, "utf8")).resolves.toBe(result.agentBase.text);
    await expect(fs.readFile(result.codexAppServerBase.path, "utf8")).resolves.toBe(
      result.codexAppServerBase.text,
    );
    await expect(fs.readFile(agentPromptPath, "utf8")).resolves.toBe(agentPrompt);
  });

  it("keeps legacy Codex template generation available", async () => {
    const result = await ensureCodexAppServerBasePromptTemplate({ stateDir: tempDir });

    await expect(fs.readFile(result.path, "utf8")).resolves.toBe(result.text);
    expect(result.text).toContain("legacy Codex app-server template alias");
  });

  it("writes the canonical global template directly", async () => {
    const result = await ensureAgentBasePromptTemplate({ stateDir: tempDir });

    await expect(fs.readFile(result.path, "utf8")).resolves.toBe(result.text);
    expect(result.text).toContain("Copy this template to an agent directory as agent-base.md");
  });
});
