import { describe, expect, it } from "vitest";
import { markGeneratedTtsLocalMediaTrusted } from "./tts-trusted-media.js";

describe("markGeneratedTtsLocalMediaTrusted", () => {
  it("trusts local media generated by TTS", () => {
    expect(
      markGeneratedTtsLocalMediaTrusted({
        input: { text: "hello" },
        output: { mediaUrl: "/tmp/openclaw/voice.opus" },
      }),
    ).toEqual({
      mediaUrl: "/tmp/openclaw/voice.opus",
      trustedLocalMedia: true,
    });
  });

  it("does not trust remote generated media URLs", () => {
    expect(
      markGeneratedTtsLocalMediaTrusted({
        input: { text: "hello" },
        output: { mediaUrl: "https://example.com/voice.opus" },
      }),
    ).toEqual({
      mediaUrl: "https://example.com/voice.opus",
    });
  });

  it("does not trust relative generated media paths", () => {
    expect(
      markGeneratedTtsLocalMediaTrusted({
        input: { text: "hello" },
        output: { mediaUrl: "../voice.opus" },
      }),
    ).toEqual({
      mediaUrl: "../voice.opus",
    });
  });

  it("does not trust mixed local and remote generated media", () => {
    expect(
      markGeneratedTtsLocalMediaTrusted({
        input: { text: "hello" },
        output: {
          mediaUrl: "/tmp/openclaw/voice.opus",
          mediaUrls: ["/tmp/openclaw/voice.opus", "https://example.com/voice.opus"],
        },
      }),
    ).toEqual({
      mediaUrl: "/tmp/openclaw/voice.opus",
      mediaUrls: ["/tmp/openclaw/voice.opus", "https://example.com/voice.opus"],
    });
  });

  it("does not trust payloads that already had media before TTS", () => {
    expect(
      markGeneratedTtsLocalMediaTrusted({
        input: { text: "hello", mediaUrl: "/tmp/openclaw/original.opus" },
        output: { text: "hello", mediaUrl: "/tmp/openclaw/original.opus" },
      }),
    ).toEqual({
      text: "hello",
      mediaUrl: "/tmp/openclaw/original.opus",
    });
  });
});
